apps/challenges/urls.py
from django.conf.urls import patterns, url
from apps.challenges import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^(?P<challenge_id>\d+)/', views.challenge_index, name='challenge'),
	url(r'^details/(?P<challenge_id>\d+)/', views.challenge_details, name='details'),
	url(r'^list/', views.challenge_list, name='list'),
	url(r'^register/', views.challenge_register, name='register'),	
	)

programaton/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'apps.core.views.index'),
    url(r'^manager/', include(admin.site.urls)),
    url(r'^accounts/', include('apps.accounts.urls', namespace='accounts')),
    url(r'^challenges/', include('apps.challenges.urls', namespace='challenges')),

)

apps/challenges/models.py
from django.db import models

# Create your models here.

apps/challenges/forms.py
from django import forms
from apps.core.models import *


class ChallengeForm(forms.ModelForm):
	"""
	Fromulario para crear torneos
	"""
	class Meta:
		model = Torneo

apps/challenges/views.py
from django.shortcuts import render_to_response, HttpResponse
from django.core.context_processors import csrf
from django.template import RequestContext 

from django.http import Http404


from apps.challenges.forms import ChallengeForm


def index(request):
	return render_to_response('challenge_index.html', {'title': 'Torneos'}, context_instance=RequestContext(request))

def challenge_index(request, challenge_id):
	#try:
		#torneo = Torneo.objects.get(id=id)
	#except Torneo.DoesNotExist:
	#	raise Http404
	#soluciones = Solucion.objects.filter(torneo=id)
	#return render_to_response('realtime.html', {'torneo': torneo, 'soluciones': soluciones}, context_instance=RequestContext(request))
	return HttpResponse("Realtime %s" % challenge_id)


def challenge_details(request, challenge_id):
	#torneo = Torneo.objects.get(pk=id)
	#return render_to_response('challenge_details.html', {'torneo': torneo, 'problemas': problemas }, context_instance=RequestContext(request))
	return HttpResponse("Detalles %s" % challenge_id)


def challenge_list(request):
	#torneos = Torneo.objects.all().order_by('-fecha_inicio')
	#return render_to_response('torneos.html', {'torneos': torneos}, context_instance=RequestContext(request))
	return HttpResponse("Listado")

	

def challenge_register(request):
    if request.POST:
        form = ChallengeForm(request.POST)
        if form.is_valid:
            form.save()
 
            return HttpResponseRedirect('/')
    else:
        form = ChallengeForm()
     
    args = {}
    args.update(csrf(request))
    
    args['form'] = form
    args['title'] = 'Crer torneo'
 
    return render_to_response('challenge_register.html', args, context_instance=RequestContext(request))
	

apps/challenges/templates/challenge.html
{% extends 'base.html' %}
{% block title %}RealTime | Programatón{% endblock %}
{% block header %}
<link rel="stylesheet" href="{{STATIC_URL}}fonts/foundation-icons.css">	
{% endblock header %}
{% block container %}
	<div class="row" style="margin-left:0%;">
	<div class="large-3 medium-4 columns">	
		<ul class="side-nav">	
			<li class="heading" style="color:#444;"><b>OPCIONES:</b></li>		
			<li>
				<i class="step fi-clipboard-pencil"style="font-size:24px;"></i>
				<a href="{% url 'core.views.detalle' torneo.id %}" target="_blank">Problemas</a>
			
			</li>			
			<li>
				<i class="step fi-checkbox"style="font-size:24px;"></i>
				<a href=''>Respuestas</a>	
			
			</li>

			<li>
				<i class="step fi-torsos-all"style="font-size:24px;"></i>
				<a href='{% url 'register.views.participante' torneo.id %}'>Participar</a>
			
			</li>	
			
			
			<li>
			<i class="step fi-lightbulb"style="font-size:24px;"></i>
			<a href='{% url 'register.views.solucion' torneo.id %}'>Enviar solución</a>
			
			</li>	
		
		</ul><!-- lista menu -->
		</div><!--columna menu -->
		<header id="header" class="">
		<h1>{{torneo.id}} : {{torneo.nombre}}</h1>
		</header><!-- /header -->
		
		<div class="large-9 medium-8 columns">
		<fieldset>			
			<div class="row">
				<div class="large-4 columns">
					<label>Hora de inicio:<input id = 'hora_inicio' type="text" name="tiempo"  class="tiempo" value="{{torneo.fecha_inicio}}" readonly></label>
				</div>
				<div class="large-4 columns">
					<label>Hora de finalización:<input id = 'hora_finalizacion' type="text" name="tiempo"  class="tiempo" value="{{torneo.fecha_finalizacion}}" readonly></label>
				</div>
				<div class="large-4 columns">
					<label>Tiempo transcurrido<input id = 'cronometro' type="text" name="tiempo"  class="tiempo" value="00:00:00" readonly></label>
				</div>
		
		
		
			</div><!-- fila formas tiempo -->
		</fieldset><!-- fieldset tiepos -->
		
	<fieldset>
	<legend>Soluciones</legend>
	<table id ='realtime'>
		<tr>
			<th>Id</th>
			<th>Nombre</th>
			<th>Fecha envio</th>
			<th>Lenguaje</th>
			<th>Alias</th>
			<th>Estado</th>
		</tr>
		{% for solucion in  soluciones %}
		<tr>
		<td>{{solucion.problema.id}}</td>
		<td>{{solucion.problema}}</td>
		<td>{{solucion.fecha_envio}}</td>
		<td>{{solucion.lenguaje}}</td>
		<td>{{solucion.friki}}</td>
		<td>{{solucion.estado}}</td>
		</tr>
		
		{%empty%}
		<tr>
		<td>Aun no se han recibido soluciones</td>
		</tr>
		{% endfor %}
	</table>
	</fieldset><!-- fieldset tabla-->
</div><!-- columna tiempos y tabla -->
</div><!--row cuerpo-->		

{% endblock%}

apps/challenges/templates/challenge_details.html
{% extends 'base.html' %}
{% block title %}Detalle Torneo  Programatón{% endblock %}
{% block container %}<h2>Torneo</h2>
	<p>Id: {{torneo.id}}</p>
	<p>Nombre: {{torneo.nombre}}</p>
	<p>Descripción: {{torneo.descripcion}}</p>
	<p>Fecha inicio: {{torneo.fecha_inicio}}</p>
	<p>Fecha finalización: {{torneo.fecha_finalizacion}}</p>
	
	<h3>Problemas:</h3>

	{% for problema in problemas %}
		<p>Id: {{problema.id}}</p>
		<p>Nombre: {{problema.nombre}}</p>
		<p>Descripción: {{problema.descripcion}}</p>
	{% empty %}
		<p>Aún no hay problemas</p>
	{% endfor %}
{% endblock%}

apps/challenges/templates/challenge_index.html
{% extends 'base.html' %}
{% block container %}
<a href="{% url 'challenges:list' %}" >Listado</a><br>
<a href="{% url 'challenges:register' %}" title="">Crear</a>
{% endblock container %}

apps/challenges/templates/challenge_list.html
{% extends 'base.html' %}
{% block title %}Torneos | Programatón{% endblock %}
{% block header %}  
{% endblock header %}
{% block container %}
<h2>Torneos</h2>
 <table>
  <tr>
    <th>Nombre</th>
    <th>Descripción</th>
    <th>Inicio</th>
    <th>Fin</th>
  </tr>  
    {% for torneo in torneos %}
    <tr>
	 	<td><a href="{% url 'core.views.detalle' torneo.id %}">{{torneo.id}}: {{torneo.nombre}}</a> <a href="{% url 'core.views.realtime' torneo.id %}">ver</a></td>
	 	<td>{{torneo.descripcion}}</td>
	 	<td>{{torneo.fecha_inicio}}</td>
	 	<td>{{torneo.fecha_finalizacion}}</td>
	 	<tr>
 	{% empty %}
 		<td>No hay torneos</td>
 		<tr>
 	{% endfor %}
</table>
{% endblock%}

apps/challenges/templates/challenge_register.html
{% extends 'base.html' %}
{% block container %}

<form method="post" accept-charset="utf-8"> {% csrf_token %}
	{{form.as_ul}}
<input type="submit" name="" value="Crear" placeholder="">
</form>

{% endblock container %}